name: Issue
description: This is for any kind of problem with the software, not just what is traditionally considered a "bug".
labels:
  - Unconfirmed
  - Not resolved
body:
  - type: checkboxes
    id: agreements
    attributes:
      label: Agreements
      options:
        - label: I have read the security policy, and i would have reported this as described there instead of as an issue if this were a security problem.
          required: true
        - label: I have read and understand the code of law which governs this project.
          required: true
        - label: I have read the contributing guidelines and understand what they mean for this report.
          required: true
  - type: markdown
    id: title_request
    attributes:
      value: "Once you have read the above agreements, please enter a title for your issue report above.  Use this _only_ to describe **the problem** you are experiencing."
  - type: dropdown
    id: version_select
    attributes:
      label: Version
      description: Support is only provided for the latest release and the latest prerelease.  If your version is not in the dropdown, either it's neither of those or we forgot to update the template.
      options:
        - 0.1.0-beta0
    validations:
      required: true
  - type: input
    id: system
    attributes:
      label: System
      description: Please describe the system in which you are using this software.
    validations:
      required: true
  - type: dropdown
    # Note:  This is used by the actions to automatically label issues with the correct category.
    id: category
    attributes:
      label: Category
      multiple: true
      options:
        - Splash files
        - Command-line program
        - libsplashtext
        - Portability
        - Documentation
        - Standards compliance
        - Optimization
        - Source code
        - General
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please comprehensively describe the issue you have found.  You can also upload any relevant files here.  You don't need to include reproduction steps.
    validations:
      required: true
